config/routes.rb
Rails.application.routes.draw do

    scope ':locale' do

  resources :syllabuses
  resources :subjects
  resources :teachers
  resources :careers
  resources :students
  
  devise_for :users

end

 authenticated :user do 
       root :to => 'students#index'
         end
   unauthenticated :user do
         devise_scope :user do
                 get "/" => "devise/sessions#new"
                     end
           end

end

app/models/student.rb
class Student < ActiveRecord::Base
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:name, :lastname, :age, :dni, :birthdate, :address, :phone, :note)
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= form_for(@student) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br>
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.text_field :age %>
  </div>
  <div class="field">
    <%= f.label :dni %><br>
    <%= f.text_field :dni %>
  </div>
  <div class="field">
    <%= f.label :birthdate %><br>
    <%= f.text_field :birthdate %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :note %><br>
    <%= f.text_field :note %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form' %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Students</h1>

<table class="table">
  <thead>
    <tr>
      <th><%= Student.human_attribute_name(:name) %></th>
      <th><%= Student.human_attribute_name(:lastname) %></th>
      <th><%= Student.human_attribute_name(:age) %></th>
      <th><%= Student.human_attribute_name(:dni)%></th>
      <th><%= Student.human_attribute_name(:birthdate)%></th>
      <th><%= Student.human_attribute_name(:address)%></th>
      <th><%= Student.human_attribute_name(:phone)%></th>
      <th><%= Student.human_attribute_name(:note)%></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td><%= student.lastname %></td>
        <td><%= student.age %></td>
        <td><%= student.dni %></td>
        <td><%= student.birthdate %></td>
        <td><%= student.address %></td>
        <td><%= student.phone %></td>
        <td><%= student.note %></td>
        <td><%= link_to 'Show', student_path(student) %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student', new_student_path %>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form' %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @student.name %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @student.lastname %>
</p>

<p>
  <strong>Age:</strong>
  <%= @student.age %>
</p>

<p>
  <strong>Dni:</strong>
  <%= @student.dni %>
</p>

<p>
  <strong>Birthdate:</strong>
  <%= @student.birthdate %>
</p>

<p>
  <strong>Address:</strong>
  <%= @student.address %>
</p>


<p>
  <strong>Phone:</strong>
  <%= @student.phone %>
</p>

<p>
  <strong>Note:</strong>
  <%= @student.note %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>