config/routes.rb
Rails.application.routes.draw do

    scope ':locale' do

  resources :syllabuses
  resources :subjects
  resources :teachers
  resources :careers
  resources :students
  
  devise_for :users

end

 authenticated :user do 
       root :to => 'students#index'
         end
   unauthenticated :user do
         devise_scope :user do
                 get "/" => "devise/sessions#new"
                     end
           end

end

app/views/layouts/_menu.html.erb
<header class="container">
  <div class="navbar navbar-default navbar-fixed-top">
    <div class="navbar-header">

      <button type="button" class="navbar-toggle " data-toggle="collapse" data-target="#acollapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

    </div>
    <!--<ul class="nav navbar-nav navbar-right">-->

    <div id ="acollapse" class="collapse navbar-collapse" >
      <a href="." class="navbar-brand">Linecodex</a>
      <ul class="nav navbar-nav  ">

      <li><%= link_to "Students", students_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Administración<span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
          <li class="nav"><%= link_to "Carreras", careers_path %></li>
          <li class="nav"><%= link_to "Profesores", teachers_path %></li>
          <li class="nav"><%= link_to "Asignatura", subjects_path %></li>
          <li class="nav"><%= link_to "Correlatividad", syllabuses_path %></li>
          </ul>
      </ul>

      <ul class="nav navbar-nav pull-right">

        <li class="nav" ><%= link_to "Cerrar Session", destroy_user_session_path, method: :delete %></li>

      </ul>
    </div>

  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Progb</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application'%>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%if user_signed_in?%>
      <%= render "layouts/menu" %>
      <div>
        <%= yield %>
      </div>
      <%= render "layouts/footer" %>
    <% else %>
      <div class="container">
        <%= yield %>
      </div>
    <% end %>


  </body>
</html>